//================================================================================
//
//		BakedSMDefines.h
//
//			A description here
//
//		Author:		Ben Yeoh
//		Date:		1/29/2012
//
//================================================================================

_DECLARE_BFX_LIB_ID(8, BAKEDSMCOMPUTE)

const uint  BAKED_SM_NUM_SH_BANDS = 4;
const uint	BAKED_SM_COMPUTE_SM_RT_LOG_SIZE = 6;
const uint	BAKED_SM_COMPUTE_SM_RT_SIZE = 1 << BAKED_SM_COMPUTE_SM_RT_LOG_SIZE;
const uint	BAKED_SM_NUM_LATENCY_BUFFERS = 3;
const float BAKED_SM_EXP_K_VAL = 3.0f;
const float BAKED_SM_MAX_FAR_PLANE = 30.0f;
const float BAKED_SM_INSIDE_DEPTH_VAL = 0.99f;

enum
{
    BAKEDSMCOMPUTE_PARABOLOID_VIEW = BAKEDSMCOMPUTE_EFFECT_PARAM_OFFSET,
    BAKEDSMCOMPUTE_FAR_PLANE,
    
    BAKEDSMCOMPUTE_TEST_LIGHT_SIZE,
    BAKEDSMCOMPUTE_TEST_LIGHT_DIST,

    BAKEDSMCOMPUTE_SPHERE_LIGHT,

    BAKEDSMCOMPUTE_AREA_LIGHTS,

    BAKEDSMCOMPUTE_AREA_LIGHT1,
    BAKEDSMCOMPUTE_AREA_LIGHT2,
    BAKEDSMCOMPUTE_AREA_LIGHT3,
    BAKEDSMCOMPUTE_AREA_LIGHT4,
    BAKEDSMCOMPUTE_AREA_LIGHT5,
    BAKEDSMCOMPUTE_AREA_LIGHT6,
    BAKEDSMCOMPUTE_AREA_LIGHT7,
    BAKEDSMCOMPUTE_AREA_LIGHT8,
    BAKEDSMCOMPUTE_AREA_LIGHT9,
    BAKEDSMCOMPUTE_AREA_LIGHT10,
    BAKEDSMCOMPUTE_AREA_LIGHT11,
    BAKEDSMCOMPUTE_AREA_LIGHT12,
    BAKEDSMCOMPUTE_AREA_LIGHT13,
    BAKEDSMCOMPUTE_AREA_LIGHT14,
    BAKEDSMCOMPUTE_AREA_LIGHT15,
    BAKEDSMCOMPUTE_AREA_LIGHT16,

    BAKEDSMCOMPUTE_END_DYNAMIC_SEMANTICS
};
 
// Effect Constant Parameter Semantics
enum
{
    BAKEDSMCOMPUTE_BAKED_SM_TEX1 = BAKEDSMCOMPUTE_EFFECT_PARAM_OFFSET + (BFX_MAX_SEMANTICS_PER_LIB >> 1),
    BAKEDSMCOMPUTE_BAKED_SM_TEX2,
    BAKEDSMCOMPUTE_BAKED_SM_TEX3,
    BAKEDSMCOMPUTE_BAKED_SM_TEX4,

    BAKEDSMCOMPUTE_BAKED_SM_VIS_SPHERE_TABLE_TEX,

    BAKEDSMCOMPUTE_BAKED_SM_EXP,    // Obviously this should just be a fixed constant
};


// Material Type ID
enum
{
    BAKEDSMCOMPUTE_MAT_OCCLUSION = BAKEDSMCOMPUTE_MATERIAL_TYPE_OFFSET,
};
