//==============================================================================
//
//		Defines.h
//
//			A description here
//
//		Author:		Ben Yeoh
//		Date:		8/4/2008
//
//==============================================================================

#pragma once

_NAMESPACE_BEGIN

_DECLARE_BFX_LIB_ID(1, SHFX)

// Effect Dynamic Parameter Semantics
enum
{
	SHFX_DIR_LIGHT_CASCADED_PROJS = SHFX_EFFECT_PARAM_OFFSET,
	SHFX_DIR_LIGHT_Z_SPLITS_NEAR,
	SHFX_DIR_LIGHT_Z_SPLITS_FAR,
	SHFX_DIR_LIGHT_CASTER_PROJ,
	
	SHFX_DIR_LIGHT_CASCADED_RT,
	
	SHFX_POINT_LIGHT_CAST_PARAMS,
	SHFX_POINT_LIGHT_SM_1,
	SHFX_POINT_LIGHT_SM_2,
	SHFX_POINT_LIGHT_SM_3,
	SHFX_POINT_LIGHT_SM_4,

	SHFX_CUBE_POINT_LIGHT_CAST_PARAMS,
	SHFX_CUBE_POINT_LIGHT_CAST_VIEW_PROJ,
	SHFX_CUBE_POINT_LIGHT_SM_1,
	SHFX_CUBE_POINT_LIGHT_SM_2,
	SHFX_CUBE_POINT_LIGHT_SM_3,
	SHFX_CUBE_POINT_LIGHT_SM_4,

	SHFX_DEBUG_EXP_AMOUNT,
	SHFX_DEBUG_OFFSET,
	SHFX_DEBUG_SM,

	SHFX_DIR_LIGHT_Z_SPLITS_VIEW_NEAR,
	SHFX_DIR_LIGHT_Z_SPLITS_VIEW_FAR,

	SHFX_DIR_LIGHT_TEX_OFFSETS,

	SHFX_END_DYNAMIC_SEMANTICS,
};

// Effect Constant Parameter Semantics
enum
{
};

//// Render Group ID
//enum
//{
//	SHFX_GROUP_PREPARE_CASCADED_DIR_LIGHT = 5000,
//	SHFX_GROUP_SHADOW_CAST_CASCADED_DIR_LIGHT_1 = 5001,
//	SHFX_GROUP_SHADOW_CAST_CASCADED_DIR_LIGHT_2 = 5002,
//	SHFX_GROUP_SHADOW_CAST_CASCADED_DIR_LIGHT_3 = 5003,
//	SHFX_GROUP_SHADOW_CAST_CASCADED_DIR_LIGHT_4 = 5004,
//	SHFX_GROUP_GAUSSIAN_H_CASCADED_DIR_LIGHT = 5005,
//	SHFX_GROUP_GAUSSIAN_V_CASCADED_DIR_LIGHT = 5006,
//	
//	SHFX_GROUP_SHADOW_CAST_PL_START = 5007,
//	SHFX_GROUP_SHADOW_CAST_PL_PREPARE = 1,
//	SHFX_GROUP_SHADOW_CAST_PL_FRONT_OFFSET = 2,
//	SHFX_GROUP_SHADOW_CAST_PL_BACK_OFFSET = 3,
//	SHFX_GROUP_GAUSSIAN_H_PL_OFFSET = 4,
//	SHFX_GROUP_GAUSSIAN_V_PL_OFFSET = 5,
//	
//	SHFX_GROUP_SHADOW_CAST_PL_OFFSET_SIZE = SHFX_GROUP_GAUSSIAN_V_PL_OFFSET - SHFX_GROUP_SHADOW_CAST_PL_PREPARE + 1,
//	SHFX_GROUP_END = 10000,
//
//	SHFX_GROUP_DEBUG_IMMEDIATE	= 0xDEADBEEF,
//	
//	//BFX_GROUP_MAIN_SETUP = 250,
//	//BFX_GROUP_OPAQUE = 260,
//	//BFX_GROUP_ALPHA_TESTED = 270,
//	//BFX_GROUP_ADDITIVE = 280,
//	//BFX_GROUP_TRANSLUCENT = 290,
//};

//// Caster flags
//enum
//{
//	SHFX_CASCADED_CASTER_0 = 0x01,
//	SHFX_CASCADED_CASTER_1 = 0x02,
//	SHFX_CASCADED_CASTER_2 = 0x04,
//	SHFX_CASCADED_CASTER_3 = 0x08,
//};

// Material Type ID
enum
{
	SHFX_MAT_CAST_DIR_LIGHT_SHADOW = SHFX_MATERIAL_TYPE_OFFSET,
	SHFX_MAT_CAST_POINT_LIGHT_SHADOW,
	SHFX_MAT_CAST_CUBE_POINT_LIGHT_SHADOW,
	SHFX_MAT_CAST_SPOT_LIGHT_SHADOW,
};

//const static float	EXP_SM_K = 40.0f;
//const static float	EXP_SM_PL_K = 8.0f;

_NAMESPACE_END
